version: '3'
services:
  server:
    build: 
        context: .
        dockerfile: server.dockerfile
    ports:
      - "5000:5000"
  nginx:
    build: 
        context: .
        dockerfile: client.dockerfile
    ports:
      - "80:80"
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=pismo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  mongo-express:
    container_name: mongo-express
    image: mongo-express    
    links: 
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=levch
      - ME_CONFIG_BASICAUTH_PASSWORD=ubuntu
    ports:
      - '8081:8081'
    volumes: 
      - ./data:/data/db 
