name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd contest_pismo && echo ${{ secrets.SERVER_PASSWORD }} | sudo -S git pull https://${{ secrets.TOKEN }}@github.com/levchCode/contest_pismo.git | docker compose stop | docker compose up --build -d
